config/routes.rb
Rails.application.routes.draw do
  resources :recommendations
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "homes#index"
   get 'recommendation/all' => 'recommendations#all'
   resources :profiles  
   resources :users, shallow: true do
    resources :receptions, shallow: true do
      resources :recommendations, shallow: true do
      
      end
    end
   end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
       return unless user.present?
       can :read, :all
       #return unless user.admin?
       #can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reception.rb
class Reception < ApplicationRecord
    belongs_to :user
    has_many :recommendation
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
    belongs_to :reception
end

app/models/role.rb
class Role < ApplicationRecord
    has_one :user_role 
    has_one :user, through: :user_role
    validates :title, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :receptions
  has_one :user_role 
  has_one :role, through: :user_role
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:phone]

         validates :phone, uniqueness: true

  def email_required?
  false
  end

  def email_changed?
  false
  end

end

app/models/user_role.rb
class UserRole < ApplicationRecord 
    belongs_to :user 
    belongs_to :role 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:phone, :role, :name, :password, :email, :password_confirmation])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:phone, :role, :name, :password, :email, :password_confirmation])
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index

  end


  private

  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :set_roles
    before_action :set_users
    before_action :set_receptions
    def index
    end


    def set_roles
        @roles = Role.all
    end
    
    def set_users
        @users = User.all
    end

    def set_receptions
        @receptions = Reception.all
    end

    
end

app/controllers/receptions_controller.rb
class ReceptionsController < ApplicationController


    def new
        @user = User.find(params[:user_id])
        @reception = Reception.new
        fast_create
    end

    def create
        @reception = Reception.new 
        @reception.user_id = @user.id
        @reception.patient = current_user.id
        @reception.activity = true
        if @reception.save
            flash[:alert] = "Успішно створено"
            redirect_to profiles_path
        else
            flash[:alert] = "Щось пішло не так"
        end
    end



    private

    

    def fast_create
        @reception = Reception.new 
        @reception.user_id = @user.id
        @reception.patient = current_user.id
        @reception.activity = true
        if @reception.save
            flash[:alert] = "Успішно створено"
            redirect_to profiles_path
        else
            flash[:alert] = "Щось пішло не так"
        end
    end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < InheritedResources::Base
  before_action :set_reception!, only: [:new, :create]




  def new
    @recommendation = Recommendation.new
  end

  def create
    @recommendation = Recommendation.new recommendation_params
    @reception.activity = false
    @recommendation.reception_id =  @reception.id
    if (@recommendation.save)
      @reception.save
        flash[:alert] = "Успішно створено"
        redirect_to profiles_path
    else
      render :new
    end
  end

  def all
    @recommendations = Recommendation.all
  end

  private

    def recommendation_params
      params.require(:recommendation).permit(:text)
    end

    def set_reception!
      @reception = Reception.find(params[:reception_id])
      
      
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def new
        @user = User.find(params[:id])
        @reception = Reception.new
    end
    
    def show
        @user = User.find(params[:id])
    end

    def create
        @reception = Reception.new 
        @reception.doctor = @user.id
        @reception.patient = current_user.id
        @reception.activity = true
        if @reception.save
            flash[:alert] = "Успішно створено"
            redirect_to profiles_path
        else
            flash[:alert] = "Щось пішло не так"
        end
    end

    def new_receptions
        @reception = Reception.new 
        @reception.doctor = @user.id
        @reception.patient = current_user.id
        @reception.activity = true
        if @reception.save
            flash[:alert] = "Успішно створено"
            redirect_to profiles_path
        else
            flash[:alert] = "Щось пішло не так"
        end

        render :nothing => true, :content_type => 'text/html', :status => 200
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/receptions_helper.rb
module ReceptionsHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/profiles/_flash.html.erb
<% flash.each do |type, msg| %>
  <div>
    <h4><%= msg %></h4>
  </div>
<% end %>

app/views/profiles/index.html.erb
<h1>Профіль</h1>
<%= render 'flash'%>
    <div>
        <%if current_user%>
            <%if current_user.role_id == nil%>
                <% @roles.each do |role| %>
                    <h3><%=role.title%></h3><br>
                    <%@users.each do |user| %>
                        <%if user.role_id == role.id%>
                            <div>
                                <%= user.name %>
                                Телефон - 
                                <%= user.phone %>
                                    <%if Reception.find_by(patient: current_user.id, user_id: user.id, activity: true) == nil and Reception.where(user_id: user.id, activity: true).count <= 10%>
                                        <%= link_to "Записатись",new_user_reception_path(user)%>
                                    <%else%>
                                        - Запис створено
                                    <%end%>
                            </div>
                        <%end%>
                    <%end%>
                    <br>
                <%end%>
            <%else%>
                <h3>Записані паціенти: </h3>
                <%@receptions.each do |reception| %>
                    <%if reception.user_id == current_user.id and reception.activity == true%>
                        <div>
                            <%=User.find(reception.patient).name%>
                            Телефон - 
                            <%=User.find(reception.patient).phone%>
                            <%=link_to "Рекомендація", new_reception_recommendation_path(reception)%>
                        </div>
                    <%end%>

                <%end%>
            <%end%>
        <%else%>
            <p>Спочатку потрібно авторизуватись</p>
        <%end%>
    </div>

app/views/receptions/_flash.html.erb
<% flash.each do |type, msg| %>
  <div>
    <h4><%= msg %></h4>
  </div>
<% end %>

app/views/receptions/new.html.erb
<h1>Запис</h1>
<%= render 'flash'%>
<div>
    <p>Посада - <%= Role.find(@user.role).title%><br>
    ПІБ - <%=@user.name%><br>
    Номер телефону  - <%=@user.phone%></p>

        <%= submit_tag "Запис на прийом", data: {turbo: false} %>


    
</div>

app/views/recommendations/_flash.html.erb
<% flash.each do |type, msg| %>
  <div>
    <h4><%= msg %></h4>
  </div>
<% end %>

app/views/recommendations/all.html.erb
<%if current_user%>
    <h1>Мої рекомендації</h1>
    <%@recommendations.each do |recommendation| %>
        <%if Reception.find(recommendation.reception_id).patient == current_user.id%> 
            <div>
                <%=User.find(Reception.find(recommendation.reception_id).user_id).name%>
                Телефон - 
                <%=User.find(Reception.find(recommendation.reception_id).user_id).phone%><br>
                <p>Рекомендація - "<%=recommendation.text%>"</p><br>

            </div>      
        <%end%>
    <%end%>
<%end%>

app/views/recommendations/new.html.erb
<%if current_user%>
  <h1>Нова рекомендація</h1>
  <%= render 'flash'%>

  <%= form_with model: [@reception, @recommendation] do |f| %>
    

    <div>
      <%= f.label :"Рекомендація", style: "display: block" %>
      <%= f.text_field :text %>
    </div>

    <div>
      <%= f.submit "Зберегти", data: {turbo: false} %>
    </div>
  <% end %>
  <br>

  <div>
    <%= link_to "Назад до профелю", profiles_path %>
  </div>
<%end%>